### PR TITLE
Timeline: Handle missing DebugUtils extension

### LINKED ISSUE #108: Timeline layer: Layer will crash if DebugUtils is not available
The current layer will crash if the debug utils extension is not available, as we cannot query instance extensions reliably on Android to test programmatically. Instead we should test if the function pointers are null, and test of that. 

Note that the layer will not do anything useful without the extension, but we can log it and handle it gracefully.

### PR DESCRIPTION
**Pull request by solidpixel**
The current code will crash if the device does not actually expose the debug utils 
extension. This PR makes the code defensive to this and will only call the functions
if they are available. Note that the layer will not be functional in terms of giving
a usable timeline, but it's a nicer user experience.

Fixes #108

### CODE REVIEW

File: layer_gpu_timeline/source/device.cpp [hunk 1]
```diff
@@ -100,6 +100,12 @@ Device::Device(Instance* _instance,
 
     initDriverDeviceDispatchTable(device, nlayerGetProcAddress, driver);
 
+    // Emit a log if debug utils entry points did not load
+    if (!driver.vkCmdBeginDebugUtilsLabelEXT)
+    {
+        LAYER_LOG("  - ERROR: Device does not expose VK_EXT_debug_utils");
```
Comment (Mark9943) [inline layer_gpu_timeline/source/device.cpp:106]: Please feel free to ignore this comment: If you can do so briefly, it might be useful to explain the consequence of this error. The word "error" doesn't seem to mean all the features of the layer driver are unavailable - for example, it appears that the layer driver will still communicate over a socket. Perhaps something like "not all features are available" might work?

**Comment by Mark9943** [comment]
Thanks for this - it looks good. I have checked everywhere I know that these functions are called.
