### PR TITLE
Use VUL safe_struct

### LINKED ISSUE #56: Create generic structure tree cloner
The Vulkan API accepts a lot of `const` pointers to input structure trees, many of which have variable content due to the use of opaque `pNext` pointers to support extensions. Layers often want to change input data before calling down the stack, and the quick and dirty way to do this quickly is just to `const_cast` the inputs and modify in place. This usually works, and has low overhead, but is obviously violating the API contract with the application and applications that reuse structures on the assumption that they are immutable will get unexpected behavior.  

The right solution here is for the layer to clone the input structure tree that it wants to modify, so that it actually owns the memory that it is modifying and knows that it is writable. We should therefore provide a common utility module that can clone an API structure tree. I suspect that this will need to be hand-written.

We should also provide a generic search utility that will return a correctly typed pointer to a structure in the pNext chain.

### PR DESCRIPTION
**Pull request by solidpixel**
The Vulkan API accepts a lot of const pointers to input structure trees, many of which have unstructured content due to the use of opaque pNext pointers to support extensions. Layers often want to change input data before calling down the stack, and the current code just uses const_cast on the inputs and modifies in place. This is obviously violating the API contract with the application so we need to fix it. 

This PR will clone structure trees where needed, using the safe_struct library from the Vulkan Utility Libraries project. 

Fixes #56

### CODE REVIEW

File: source_common/framework/manual_functions.cpp [hunk 1]
```diff
@@ -448,10 +438,8 @@ static void enableDeviceVkKhrTimelineSemaphore(VkDeviceCreateInfo& createInfo,
     // Add a config if not configured by the application
     if (!config1 && !config2)
     {
-        newFeatures.pNext = const_cast<void*>(createInfo.pNext);
-        newFeatures.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TIMELINE_SEMAPHORE_FEATURES;
         newFeatures.timelineSemaphore = true;
-        createInfo.pNext = reinterpret_cast<const void*>(&newFeatures);
+        vku::AddToPnext(createInfo, newFeatures);
```
Comment (solidpixel) [inline source_common/framework/manual_functions.cpp:442]: This takes a copy, so we don't need the original on the stack as a parameter, so move it in to here.
